### PR TITLE
Noughts & Crosses 

### PR DESCRIPTION
**Pull request by MaddPaige**
wanting to make noughts & crosses playable.

### CODE REVIEW

**Comment by sehsarah** [comment]
Hey @MaddPaige Can this be created as an Issue in your repo? With a brief written out about how you'd like the noughts & crosses to work - remember to use screenshots and bullet points

**Comment by MaddPaige** [comment]
Hey @sehsarah  I think I have done this now here is the link for my issue ithttps://github.com/MaddPaige/Grandma-Mcgarvey-/issues/1#issue-500534491

Thank you

**Comment by sehsarah** [comment]
I think you need to add me as a contributor to your repo @MaddPaige , in settings

**Comment by MaddPaige** [comment]
I think I have sent you an invite @sehsarah , Thank you

**Pull request closed without merging**
